### ISSUE TITLE
Crosspost not running due to stored .env variable

### ISSUE THREAD

**Issue by theuiguru** [humanwhocodes/crosspost#16]
After running the following code with dotenv variables, I got the following error about missing password even though I stored it secretly in my .env file:
![image](https://github.com/user-attachments/assets/df9a45f7-5c0e-420a-a8de-5857e665af10)

I even debugged it by updating npm versions from 22 to 20 and back, as well as updating the crosspost npm package versions from 0.2.0 to 0.1.1 and back, but still same error persists. Can crosspost still work with dotenv variables?

```
import {
	Client,
	TwitterStrategy,
	BlueskyStrategy,
} from "@humanwhocodes/crosspost";

// Note: Use an app password, not your login password!
const bluesky = new BlueskyStrategy({
	identifier: "[username].bsky.social",
	password: process.env.BSKY_APP_PASSWORD,
	host: "bsky.social", // "bsky.social" for most people
});

// Note: OAuth app is required
const twitter = new TwitterStrategy({
	accessTokenKey: process.env.TX_ACCESS_TOKEN,
	accessTokenSecret: process.env.TX_ACCESS_TOKEN_SECRET,
	apiConsumerKey: process.env.TX_API_CONSUMER_KEY,
	apiConsumerSecret: process.env.TX_CONSUMER_SECRET,
});

// create a client that will post to all three
const client = new Client({
	strategies: [bluesky, twitter],
});

// post to all two
await client.post("Success in crossposting to X and Bluesky!");
```

**Comment by nzakas** [comment]
Yes it can. Node.js doesn't automatically read in `.env`, so you need to install `dotenv` and then enable it:

```js
import * as dotenv from "dotenv";

dotenv.config();
```
